[2025-06-29T11:52:52.720+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2021-12-29T00:00:00+00:00 [None]>
[2025-06-29T11:52:52.767+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator_v03.insert_into_table scheduled__2021-12-29T00:00:00+00:00 [None]>
[2025-06-29T11:52:52.774+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2025-06-29T11:52:52.851+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_table> on 2021-12-29 00:00:00+00:00
[2025-06-29T11:52:52.935+0000] {standard_task_runner.py:57} INFO - Started process 3842 to run task
[2025-06-29T11:52:52.941+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator_v03', 'insert_into_table', 'scheduled__2021-12-29T00:00:00+00:00', '--job-id', '478', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpmzp5ifb_']
[2025-06-29T11:52:52.950+0000] {standard_task_runner.py:85} INFO - Job 478: Subtask insert_into_table
[2025-06-29T11:52:54.823+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-06-29T11:52:55.012+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
