[2025-06-29T15:20:36.550+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-29T15:21:01.651+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v01.get_sklearn scheduled__2022-05-25T00:00:00+00:00 [queued]>
[2025-06-29T15:21:02.146+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_dependencies_v01.get_sklearn scheduled__2022-05-25T00:00:00+00:00 [queued]>
[2025-06-29T15:21:02.178+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-06-29T15:21:03.019+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): get_sklearn> on 2022-05-25 00:00:00+00:00
[2025-06-29T15:21:03.480+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependencies_v01', 'get_sklearn', 'scheduled__2022-05-25T00:00:00+00:00', '--job-id', '4570', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_dependencies.py', '--cfg-path', '/tmp/tmpba57y9g_']
[2025-06-29T15:21:03.771+0000] {standard_task_runner.py:91} INFO - Job 4570: Subtask get_sklearn
[2025-06-29T15:21:03.809+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=228) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-29T15:21:03.864+0000] {standard_task_runner.py:63} INFO - Started process 248 to run task
[2025-06-29T15:21:11.187+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_python_dependencies_v01.get_sklearn scheduled__2022-05-25T00:00:00+00:00 [running]> on host 10ba4c57dcb8
[2025-06-29T15:21:24.550+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='shivanshu' AIRFLOW_CTX_DAG_ID='dag_with_python_dependencies_v01' AIRFLOW_CTX_TASK_ID='get_sklearn' AIRFLOW_CTX_EXECUTION_DATE='2022-05-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-05-25T00:00:00+00:00'
[2025-06-29T15:21:26.209+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-29T15:26:51.342+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to None. Terminating instance.
[2025-06-29T15:26:57.557+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-29T15:27:05.748+0000] {process_utils.py:132} INFO - Sending 15 to group 248. PIDs of all processes in the group: [248]
[2025-06-29T15:27:17.079+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 248
[2025-06-29T15:27:49.244+0000] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-06-29T15:27:58.011+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-29T15:28:16.555+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_with_python_dependencies.py", line 15, in get_sklearn
    import sklearn
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/__init__.py", line 73, in <module>
    from .base import clone  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/base.py", line 19, in <module>
    from .utils._metadata_requests import _MetadataRequester, _routing_enabled
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/__init__.py", line 9, in <module>
    from ._chunking import gen_batches, gen_even_slices
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_chunking.py", line 11, in <module>
    from ._param_validation import Interval, validate_params
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 17, in <module>
    from .validation import _is_arraylike_not_scalar
  File "/home/airflow/.local/lib/python3.12/site-packages/sklearn/utils/validation.py", line 15, in <module>
    import joblib
  File "/home/airflow/.local/lib/python3.12/site-packages/joblib/__init__.py", line 116, in <module>
    from ._store_backends import StoreBackendBase
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1124, in get_code
  File "<frozen importlib._bootstrap_external>", line 753, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2609, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-06-29T15:28:20.053+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dag_with_python_dependencies_v01, task_id=get_sklearn, execution_date=20220525T000000, start_date=20250629T152101, end_date=20250629T152819
[2025-06-29T15:28:31.453+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=248, status='terminated', exitcode=2, started='15:21:02') (248) terminated with exit code 2
